# Generated by Django 3.1.7 on 2021-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classroom_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hour',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
