# Generated by Django 3.1.7 on 2021-04-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210403_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practical',
            old_name='title',
            new_name='name',
        ),
    ]
