# Generated by Django 3.1.7 on 2021-04-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210403_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hour',
            old_name='hour',
            new_name='name',
        ),
    ]
