# Generated by Django 3.1.7 on 2021-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_publisher_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='practical',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
