# Generated by Django 3.1.7 on 2021-04-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
