# Generated by Django 3.1.7 on 2021-04-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210403_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
    ]
